server:
  port: ${rookie-im.user.server.port}
  servlet:
    context-path: /v1/api
spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: rookie-im-api-user
  datasource:
    url: jdbc:mysql://${rookie-im.mysql.ip}:${rookie-im.mysql.port}/${rookie-im.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${rookie-im.mysql.username}
    password: ${rookie-im.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# logger 配置
logging:
  config: classpath:logback-spring.xml

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

# rookie 项目自定义配置
rookie:
  im:
    rule:
      xssRule:
        enabled: true
        order: 0
      authRule:
        order: 10

# jwt 配置
jwt:
  accessToken:
    expireIn: ${rookie-im.jwt.access.expireIn} #半个小时
    secret: ${rookie-im.jwt.access.secret}
  refreshToken:
    expireIn: ${rookie-im.jwt.refresh.expireIn} #7天
    secret: ${rookie-im.jwt.refresh.secret}

# RSA 配置
rsa:
  public-key: ${rookie-im.rsa.publicKey}
  private-key: ${rookie-im.rsa.privateKey}
